services:
  - docker

jobs:
  include:
    - stage: build
      language: minimal
      script:
        - docker build . -t shu-course
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker tag shu-course $DOCKER_USERNAME/shu-course:$TRAVIS_BUILD_ID
        - docker push $DOCKER_USERNAME/shu-course
